package entity

import java.util.Date

data class RemuneracaoDTO(
    val skMesReferencia: Date,
    val mesAno: String,
    val valorTotalRemuneracaoAposDeducoes: String,
    val valorTotalRemuneracaoDolarAposDeducoes: String,
    val valorTotalJetons: String,
    val valorTotalHonorariosAdvocaticios: String,
    val rubricas: List<RubricaDTO>,
    val jetons: List<JetomDTO>,
    val honorariosAdvocaticios: List<HonorariosAdvocaticiosDTO>,
    val observacoes: List<String>,
    val remuneracaoBasicaBruta: String,
    val remuneracaoBasicaBrutaDolar: String,
    val abateRemuneracaoBasicaBruta: String,
    val abateRemuneracaoBasicaBrutaDolar: String,
    val gratificacaoNatalina: String,
    val gratificacaoNatalinaDolar: String,
    val abateGratificacaoNatalina: String,
    val abateGratificacaoNatalinaDolar: String,
    val ferias: String,
    val feriasDolar: String,
    val outrasRemuneracoesEventuais: String,
    val outrasRemuneracoesEventuaisDolar: String,
    val impostoRetidoNaFonte: String,
    val impostoRetidoNaFonteDolar: String,
    val previdenciaOficial: String,
    val previdenciaOficialDolar: String,
    val outrasDeducoesObrigatorias: String,
    val outrasDeducoesObrigatoriasDolar: String,
    val pensaoMilitar: String,
    val pensaoMilitarDolar: String,
    val fundoSaude: String,
    val fundoSaudeDolar: String,
    val taxaOcupacaoImovelFuncional: String,
    val taxaOcupacaoImovelFuncionalDolar: String,
    val verbasIndenizatoriasCivil: String,
    val verbasIndenizatoriasCivilDolar: String,
    val verbasIndenizatoriasMilitar: String,
    val verbasIndenizatoriasMilitarDolar: String,
    val verbasIndenizatoriasReferentesPDV: String,
    val verbasIndenizatoriasReferentesPDVDolar: String,
    val remuneracaoEmpresaPublica: Boolean,
    val existeValorMes: Boolean,
    val mesAnoPorExtenso: String,
    val verbasIndenizatorias: String,
    val verbasIndenizatoriasDolar: String,
)
